openapi: 3.0.0
info:
  version: '1.0'
  title: "Ingegneria del software OpenAPI 3.0"
  description: API del progetto relativo al corso di ingegneria del software.
  license:
    name: MIT
servers:
  - url: http://localhost:3000/api/v1
    description: Localhost
            
paths:
  /maf:
    post:
      description: Registra un nuovo MAF nella piattaforma
      summary: Registra un nuovo MAF nella piattaforma
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - nome
                - cognome
                - codiceFiscale
                - email
              properties:
                nome:
                  type: string
                  description: 'Nome del MAF'
                cognome:
                  type: string
                  description: 'Cognome del MAF'
                codiceFiscale:
                  type: string
                  description: 'Codice fiscale del MAF'
                email:
                  type: string
                  description: 'Indirizzo email del MAF, utilizzato per il login'
      responses:
        '201':
          description: 'MAF creato. Locazione della risorsa nel campo self'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '400':
          description: 'Non sono stati specificati i parametri obbligatori nel corpo della richiesta'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '409':
          description: 'È già presente un MAF registrato nel sistema oppure l''indirizzo e-mail o il codice fiscale inseriti sono già presenti nell''elenco degli utenti. Non è possibile procedere alla creazione di un ulteriore MAF'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '500':
          description: 'Errore nel salvataggio dei dati nel database. Il MAF non è stato creato'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
    get:
      description: Esegui il login per il MAF alla piattaforma
      summary: Esegui il login per il MAF alla piattaforma
      
      parameters:
        - in: header
          name: X-Access-Token
          description: Token JWT fornito da Firebase (nel frontend è memorizzato in un cookie)
          schema:
            type: string
            format: string
          required: true

      responses:
        '202':
          description: 'MAF loggato.' 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '400':
          description: 'Token mancante nella richiesta'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '401':
          description: 'Indirizzo e-mail utente non riconosciuto'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '403':
          description: 'Indirizzo e-mail utente riconosciuto, ma non è Manager di Federazione'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '500':
          description: 'Errore durante il controllo del token'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
  
  
  /setuptorneo:
    post:
      description: Crea un nuovo torneo con i parametri passati nella richiesta
      summary: Crea un nuovo torneo con i parametri passati nella richiesta
      
      parameters:
        - in: header
          name: X-Access-Token
          description: Token JWT fornito da Firebase (nel frontend è memorizzato in un cookie)
          schema:
            type: string
            format: string
          required: true
          
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Torneo'
      
      responses:
        '201':
            description: 'Torneo creato correttamente.' 
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/RispostaJSON'
        '400':
          description: 'Token mancante nella richiesta o campi necessari alla creazione torneo mancanti'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '401':
          description: 'Indirizzo e-mail utente non riconosciuto'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '403':
          description: 'Indirizzo e-mail utente riconosciuto, ma non è Manager di Federazione'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '500':
          description: 'Errore durante il controllo del token o errore durante il salvataggio del torneo'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
          
      
            
            
      
                
  /arbitro:
    post:
      description: Registra un nuovo arbitro nella piattaforma
      summary: Registra un nuovo arbitro nella piattaforma
      
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - nome
                - cognome
                - codiceFiscale
                - email
              properties:
                nome:
                  type: string
                  description: 'Nome dell''arbitro'
                cognome:
                  type: string
                  description: 'Cognome del''arbitro'
                codiceFiscale:
                  type: string
                  description: 'Codice fiscale del''arbitro'
                email:
                  type: string
                  description: 'Indirizzo email del''arbitro, utilizzato per il login'
                sezione:
                  type: string
                  description: 'Sezione'
                codicePatentino:
                  type: string
                  description: 'Codice patentino'
      responses:
        '201':
          description: 'Arbitro creato. Locazione della risorsa nel campo self'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '400':
          description: 'Non sono stati specificati i parametri obbligatori nel corpo della richiesta'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '409':
          description: 'L''indirizzo e-mail o il codice fiscale inseriti sono già presenti nell''elenco degli utenti. Non è possibile salvare l''arbitro'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '500':
          description: 'Errore nel salvataggio dei dati nel database. Il MAF non è stato creato'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
    
    
components:
 schemas:
    RispostaJSON:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        error:
          type: string
        self:
          type: string
    Utente:
      type: object
      required:
        - _id
        - nome
        - cognome
        - codiceFiscale
        - email
        - ruolo
        - stato
        - sezione
        - codicePatentino
        - approvato
      properties:
        _id:
          type: string
          description: 'Identificativo univoco dell''utente'
        nome:
          type: string
          description: 'Nome'
        cognome:
          type: string
          description: 'Cognome'
        codiceFiscale:
          type: string
          description: 'Codice fiscale'
        email:
          type: string
          description: 'Indirizzo email. Viene utilizzato per il login'
        ruolo:
          type: string
          description: 'Ruolo del''utente. Può essere: manager, arbitro o giocatore'
          enum:
          - manager
          - arbitro
          - giocatore
        stato:
          type: string
          description: 'Stato dell''utente di tipo giocatore'
          enum:
          - in_attesa
          - approvato
          - sostituito
        sezione:
          type: string
          description: 'Sezione dell''utente di tipo arbitro'
        codicePatentino:
          type: string
          description: 'Codice patentino dell''utente di tipo arbitro'
        approvato:
          type: boolean
          description: 'Stato di approvazione dell''utente di tipo arbitro'
    Torneo:
      type: object
      required:
        - numero_gironi
        - numero_squadre
        - squadre_per_girone
        - alle_fasi_finali
      properties:
        numero_gironi:
          type: integer
          description: numero di gironi che compongono il torneo
          enum:
          - 4
          - 8
        numero_squadre:
          type: integer
          description: numero delle squadre che possono partecipare al torneo
        squadre_per_girone:
          type: integer
          description: numero di squadre che compongono ogni girone
        alle_fase_finali:
          type: integer
          description: numero di squadre che per ogni girone accedono alle fasi finali
          enum:
          - 1
          - 2