openapi: 3.0.0
info:
  version: '1.0'
  title: "Ingegneria del software OpenAPI 3.0"
  description: API del progetto relativo al corso di ingegneria del software.
  license:
    name: MIT
servers:
  - url: http://localhost:3000/api/v1
    description: Localhost
            
paths:
  /maf:
    post:
      description: Registra un nuovo MAF nella piattaforma
      summary: Registra un nuovo MAF nella piattaforma
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - nome
                - cognome
                - codiceFiscale
                - email
              properties:
                nome:
                  type: string
                  description: 'Nome del MAF'
                cognome:
                  type: string
                  description: 'Cognome del MAF'
                codiceFiscale:
                  type: string
                  description: 'Codice fiscale del MAF'
                email:
                  type: string
                  description: 'Indirizzo email del MAF, utilizzato per il login'
      responses:
        '201':
          description: 'MAF creato. Locazione della risorsa nel campo self'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '400':
          description: 'Non sono stati specificati i parametri obbligatori nel corpo della richiesta'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '409':
          description: 'È già presente un MAF registrato nel sistema. Non è possibile procedere alla creazione di un ulteriore MAF'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
        '500':
          description: 'Errore nel salvataggio dei dati nel database. Il MAF non è stato creato'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaJSON'
components:
 schemas:
   RispostaJSON:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
        error:
          type: string
        self:
          type: string
   Utente:
     type: object
     required:
       - _id
       - nome
       - cognome
       - codiceFiscale
       - email
       - ruolo
       - stato
       - sezione
       - codicePatentino
       - approvato
     properties:
       _id:
         type: string
         description: 'Identificativo univoco dell''utente'
       nome:
          type: string
          description: 'Nome'
       cognome:
          type: string
          description: 'Cognome'
       codiceFiscale:
          type: string
          description: 'Codice fiscale'
       email:
         type: string
         description: 'Indirizzo email. Viene utilizzato per il login'
       ruolo:
         type: string
         description: 'Ruolo del''utente. Può essere: manager, arbitro o giocatore'
         enum:
         - manager
         - arbitro
         - giocatore
       stato:
         type: string
         description: 'Stato dell''utente di tipo giocatore. Può essere: ' # TODO: inserire i valori possibili
       sezione:
         type: string
         description: 'Sezione dell''utente di tipo arbitro'
       codicePatentino:
         type: string
         description: 'Codice patentino dell''utente di tipo arbitro'
       approvato:
         type: boolean
         description: 'Stato di approvazione dell''utente di tipo arbitro'
          
#components:
#  schemas:
#    Student:
#      type: object
#      required:
#        - id
#        - email
#      properties:
#        id:
#          type: integer
#          description: 'ID of the user'
#        email:
#          type: string
#          description: 'Email address of the user'
#    Book:
#      type: object
#      required:
#        - title
#        - author
#        - ISBN
#        - status
#      properties:
#        title:
#          type: string
#          description: 'Title of the book'
#        deadline:
#          type: string
#          description: 'Author of the book'
#        ISBN:
#          type: string
#          description: 'ISBN of the book'
#        status:
#          type: string
#          enum: [available, lended]
#          description: 'Tells whether the book is currently available or not'
#    Booklending:
#      type: object
#      required:
#      - student
#      - book
#      properties:
#        user:
#          type: string
#          description: 'Link to the user'
#        book:
#          type: integer
#          description: 'Link to the book'